# Generated by Django 3.2 on 2022-05-27 19:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SensorItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pressure', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('avg_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weather.sensor')),
            ],
        ),
    ]
