# Generated by Django 3.2 on 2022-05-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoritems',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
