# Generated by Django 3.2 on 2022-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20220528_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoritems',
            name='avg_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
