# Generated by Django 3.2 on 2022-05-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_sensoritems_avg_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorItems',
        ),
    ]
